#!/bin/bash
cd ~
#install node-js
apt-get install nodejs
#install express to make code simpler -g means global
npm install -express-generator
#configure express to use stylus for css
express -c stylus express_example
#install dependencies 
cd express_example && npm install
#run app should see output "listening on port 3000"
DEBUG=express_example:* npm start
#set up git
#git init
#echo 'node_modules' > .gitignore
#git add 
#git commit -m 'initial commit'
git clone https://github.com/corysterner/css_and_html
#use nodemon to make it so it doesn't have to restart with change
npm install -g nodemon
#now start app with DEBUG=express_example:* nodemon
